___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

### Create an array of 10 zeros 

In [4]:
a1=np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
a1=np.ones(10)
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
a1=np.ones(10)*5
a1

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [ ]:
a1=np.arange(10,51)
a1

#### Create an array of all the even integers from 10 to 50

In [7]:
a1=np.arange(10,51,2)
a1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
a1=np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [11]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand()

0.943051628882346

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [13]:
a=np.random.rand(25)
a

array([0.46717281, 0.14949069, 0.93903434, 0.37841273, 0.95827671,
       0.79111603, 0.15071462, 0.99831515, 0.37541518, 0.59413173,
       0.61326895, 0.33738047, 0.59131593, 0.00490012, 0.63452655,
       0.06361877, 0.33090678, 0.2492381 , 0.88989089, 0.12363229,
       0.18904512, 0.80806161, 0.93693355, 0.24693528, 0.58146619])

#### Create the following matrix:

In [14]:
a=np.random.rand(25).reshape(5,5)
a

array([[0.51247349, 0.74189474, 0.38999659, 0.29465439, 0.97666795],
       [0.01013509, 0.23220971, 0.81121223, 0.7790055 , 0.50547089],
       [0.9365182 , 0.91304091, 0.955727  , 0.06006716, 0.08484538],
       [0.32423078, 0.23651617, 0.67702374, 0.1525995 , 0.8900095 ],
       [0.85677058, 0.90168287, 0.7922135 , 0.05059945, 0.42731551]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [15]:
a=np.linspace(0,1,20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [16]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3,4]

20

20

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[:,1].reshape((5,1))

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [21]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[4,:]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])